import Head from 'next/head';
import Header from "../components/Header";
import Footer from '../components/Footer';
import HeroBanner from '../components/HeroBanner';
import About from '../components/About';
import WaterAccess from '../components/WaterAccess';
import Subscribe from '../components/Subscribe';

export default function test() {
  return (
    <div>
      <Head>
        <title>Quench</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <HeroBanner/>
        <About/>
        <WaterAccess/>
        <Subscribe/>
      </main>
      <Footer />
    </div>
  )
}
